### ISSUE TITLE
手动安装出错

### ISSUE THREAD

**Issue by YLXDXX** [yutent/sonist#5]
错误如下：
`> electron@4.0.1 postinstall /home/shui/Desktop/sonist-master/node_modules/electron
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN sonist@0.9.0 No repository field.

added 321 packages in 13.069s
`
请问可有解决之法？

**Comment by YLXDXX** [comment]
谢了，原来是网络问题，不过我在路由端挂全局代理问题依旧

**Comment by yutent** [comment]
把错误信息都贴出来看看

**Comment by YLXDXX** [comment]
er...出错的跟前面一样，居然发布安装包了，感谢，方便了小白，除了使用有点不习惯外还好，不过感觉对歌词匹配有点不准确，很多歌都需要手动调整歌词，或者手动选择歌词，还有一个就是对音乐的扫描加载太慢了（几百首歌加载了几分钟）

**Comment by YLXDXX** [comment]
桌面歌词上面有个 小锁，不过打开和关闭都一样，都不能记住前面的设定，重新启动程序后位置又恢复默认了

**Comment by YLXDXX** [comment]
还有就是每次切歌都需要打开主页面，在右下角的托盘中没法直接用鼠标切换，不过等你的多媒体快捷键完成或许就方便了

**Comment by yutent** [comment]
扫描音乐慢是因为要检查文件的hash值,因为要用这个来确保不会重复, 暂时也没啥好办法。 好在也不用整天扫描音乐, 所以先这样了。
/* ----------------------- */
桌面歌词的小锁, 是禁止拖动的功能(不支持linux)。位置记忆这个问题, 后面看看要不要做了。
/* ----------------------- */
切歌的话, 后面 会有快捷键。 其他有顶栏的系统, 后面也会在顶栏上加按钮, deepin没有顶栏这种东东, 就只能是 快捷键了。
