### ISSUE TITLE
专辑图片不要转

### ISSUE THREAD

**Issue by sonichy** [yutent/sonist#9]
转动CPU占用高，搞个设置也行。
桌面歌词能不能单排？调大小？调颜色？
点击软件内的链接会打开的新窗口，由于没有无边框无法关闭，建议取消链接，并将链接明码，或者在系统浏览器打开。

**Comment by yutent** [comment]
1、转动这个cpu占用高, 大概只有dde才会出现了, 这跟dde的UI渲染有关, 挥一下鼠标我的cpu都能跑到80%去。 我自己用mint, 完全没这个问题。  这个我后面会着重优化一下,  后面会加个动画特效开关, 在dde下把所有的动画, 图像特效全关闭, 这样应该能正常一点。

2、桌面歌词, 大概不会做单排了; 颜色修改可以加。
     不过桌面歌词功能, 其实使用率并不高。在mac/linux下, 桌面正常都是多工作区模式, 除非让歌词在所 有的工作区上都显示, 不过这做法不太合理。所以我是打算做 `顶栏歌词` 的, 只是dde没有顶栏, 大概在dde上不会有这功能了。

3、 内部链接打开这个, 因为当前版本只是体验版, 所以还没开发到这里, 只是为了可能临时加上去的东东, 后面 设置页面会重新规划和设计的。


/* ==========

目前的1.x版 仍然还是 体验版的, 在Readme.md上有开发进度和计划。 真正的正式版, 大概会以 2.x开始。
目前的 体验版, 只用于 建议收集的bug反馈。
